# Generated by Django 4.0.5 on 2022-10-22 12:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes_of_meeting',
            name='additional_members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='minutes_of_meeting',
            name='venue',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
