# Generated by Django 4.0.5 on 2022-10-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_minutes_of_meeting_additional_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes_of_meeting',
            name='description',
            field=models.CharField(max_length=4096),
        ),
    ]
