version: '3.9'
services:

  dash_db: 
    # UPON DEPLOYMENT: restart: always
    image: postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: "localhost"
    expose:
      - 5440
    ports:
      - 5440:5432 
    volumes:
      - dash_db:/var/lib/postgresql/data

volumes:
  dash_db: